specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: "DAO"Governor
    network: {{ network }}
    source:
      address: "{{ governorContractAddress }}"
      abi: "DAO"Governor
      startBlock: {{ governorContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: "DAO"Governor
          file: ./abis/"dao"-governance/"DAO"Governor.json
      eventHandlers:
        - event: ProposalCanceled(uint256)
          handler: handleProposalCanceled
        - event: ProposalCreated(uint256,address,address[],uint256[],string[],bytes[],uint256,uint256,string)
          handler: handleProposalCreated
        - event: ProposalExecuted(uint256)
          handler: handleProposalExecuted
        - event: ProposalQueued(uint256,uint256)
          handler: handleProposalQueued
        - event: QuorumNumeratorUpdated(uint256,uint256)
          handler: handleQuorumNumeratorUpdated
        - event: TimelockChange(address,address)
          handler: handleTimelockChange
        - event: VoteCast(indexed address,uint256,uint8,uint256,string)
          handler: handleVoteCast
      file: ./protocols/"dao"-governance/src/"dao"-governor.ts
  - kind: ethereum/contract
    name: "DAO"Token
    network:  {{ network }}
    source:
      address: "{{ tokenContractAddress }}"
      abi: "DAO"Token
      startBlock: {{ tokenContractStartBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Governance
        - Proposal
        - Vote
        - TokenHolder
        - Delegate
      abis:
        - name: "DAO"Token
          file: ./abis/"dao"-governance/"DAO"Token.json
      eventHandlers:
        - event: DelegateChanged(indexed address,indexed address,indexed address)
          handler: handleDelegateChanged
        - event: DelegateVotesChanged(indexed address,uint256,uint256)
          handler: handleDelegateVotesChanged
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/"dao"-governance/src/"dao"-token.ts
